import { themeColors } from '@/lib/terminal/commands/theme/themeColors';

export const manual = {
  apt: [
    'apt',
    'Advanced Package Tool (APT) - A package management system for Debian-based Linux distributions.',
    '',
    'Syntax',
    'apt [options] command',
    '',
    'Description',
    'apt provides a high-level commandline interface for the package management system. It is intended as an end user interface and enables some options better suited for interactive usage by default compared to more specialized APT tools like apt-get(8) and apt-cache(8).',
    '',
    'Options',
    'The options are as follows:',
    '',
    'Global options',
    'These options are used in various places and can be used with any of the commands:',
    '',
    '-c, --config-file= Configuration File',
    'Use the given configuration file. The configuration file is a set of lines with the format "Option: Value".',
    '',
    '-o, --option= Set a Configuration Option',
    'Set a Configuration Option. This will set an arbitrary configuration option. The syntax is -o Foo::Bar=bar.',
    '',
    '-h, --help',
    'Show a short usage summary.',
    '',
    '-v, --version',
    'Show the program version.',
    '',
    'Commands',
    'The following commands are available:',
    '',
    'apt-get',
    'apt-get is the command-line tool for handling packages, and may be considered the user\'s "back-end" to other tools using the APT library. Several "front-end" interfaces exist, such as aptitude(8), synaptic(8) and wajig(1).',
    '',
    'apt-key',
    'apt-key is used to manage the list of keys used by apt to authenticate packages. Packages which have been authenticated using these keys will be considered trusted.',
    '',
    'apt-cache',
    "apt-cache is a low-level tool used to query information from APT's package cache.",
    '',
    'apt-config',
    'apt-config is an internal program used by various APT-based utilities to provide consistent configuration.',
    '',
    'apt-mark',
    'apt-mark is a utility to change the settings in the dpkg database.',
    '',
    'apt-secure',
    'apt-secure is a program that is used to manage the configuration of the APT authentication system.',
    '',
    'apt-extracttemplates',
    'apt-extracttemplates is used by debconf',
    '',
    'apt-ftparchive',
    'apt-ftparchive is a program that generates index files for Debian archives.',
    '',
    'apt-sortpkgs',
    'apt-sortpkgs is a simple tool to sort package index files.',
    '',
    'apt-listchanges',
    'apt-listchanges is a tool to show what has been changed in a new version of a package.',
    '',
    'apt-config',
    'apt-config is a simple tool to read the APT configuration file.',
    '',
    '"The only way to do great work is to love what you do." ~ Steve Jobs',
  ],
  cd: [
    'cd',
    'Change Directory - change the current working Folder.',
    '',
    'Syntax',
    'cd [-L|-P] [dir]',
    '',
    'Key',
    '-P Use the physical directory structure instead of following symbolic links (see also the -P option to the set builtin command)',
    '-L Force symbolic links to be followed',
    'If a dir is given, changes the shell’s working directory to dir. If not, changes to HOME (shell variable).',
    '$ cd - will go back to the last folder you looked at. This does not stack, so issuing CD - repeatedly will just toggle between two directories, to go back further use pushd/popd. Previous directory - equivalent to $OLDPWD',
    './ or just . is shorthand for the current directory.',
    'CDPATH',
    'The shell variable CDPATH provides a useful feature, this variable is similar to PATH but it sets up a list of paths where cd will search for subdirectories. CDPATH can be set on the command line for use in the current session, or in .bash_profile for permanent use, the list of paths must be colon separated (:)',
    '$ CDPATH=".:~:~/Library"',
    'If dir begins with a slash (/), then CDPATH is not used.',
    'If a non-empty directory name from CDPATH is used, or if - is the first argument, and the directory change is successful, the absolute pathname of the new working directory is written to the standard output.',
    'The return value is true if the directory was successfully changed; false otherwise.',
    'This is a BASH shell builtin, to display your local syntax from the bash prompt type: help cd',
    '',
    'Examples',
    'Move to a subfolder named "Documents":',
    '$ cd Documents',
    'Move to the fonts folder:',
    '$ cd /library/fonts',
    '$ pwd',
    'cd /library/fonts',
    'Change to another folder:',
    '$ cd ~/music',
    '$ pwd',
    '/Users/kate/music',
    'Move up to the parent directory (/Users/kate/):',
    'cd ..',
    'Move up two levels:',
    '$ cd ../..',
    'Move to the top of the boot volume:',
    '$ cd /',
    'Move to your home directory:',
    '$ cd ~',
    'or just:',
    '$ cd',
    'Move to a folder when the folder name includes spaces, parentheses or any other punctuation:',
    "$ cd 'AppleWorks User Data'",
    '',
    '“In times of change, learners inherit the earth, while the learned find themselves equipped to deal with a world that no longer exists” ~ Eric Hoffer',
  ],
  clear: [
    'clear',
    'NAME',
    'clear - clear the terminal screen',
    '',
    'SYNOPSIS',
    'clear',
    '',
    'DESCRIPTION',
    'clear clears your screen if this is possible. It looks in the environment for the terminal type and then in the terminfo database to figure out how to clear the screen.',
    'clear ignores any command-line parameters that may be present.',
  ],
  commands: [
    'commands',
    'List all Available Commands - Display a list of all commands that can be used.',
    '',
    'Syntax',
    'commands',
    '',
    'Description',
    "The 'commands' command lists all the available commands that the user can execute. It is typically used to get a quick overview of the functionalities provided by the system or application.",
    '',
    'Options',
    'There are no options for this command; it simply lists all available commands when executed without any parameters.',
    '',
    'Output',
    'The output is a list of commands with a brief description of what each command does.',
    '',
    'Examples',
    'To list all available commands:',
    '$ commands',
    '',
    'Notes',
    "The 'commands' command does not take any arguments or flags. It provides a straightforward way to discover the commands accessible in the current context.",
    '',
    '“Knowledge is power.” ~ Francis Bacon',
  ],
  df: [
    'df',
    'Display free disk space.',
    '',
    'Syntax',
    'df [OPTION]... [FILE]...',
    '',
    'Description',
    'This manual page documents the GNU version of df. df displays the amount of disk space available on the file system containing each file name argument. If no file name is given, the space available on all currently mounted file systems is shown.',
    '',
    'Options',
    '-a, --all             include pseudo, duplicate, inaccessible file systems',
    '-B, --block-size=SIZE  use SIZE-byte blocks',
    '-h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)',
    '-H, --si              likewise, but use powers of 1000 not 1024',
    '-i, --inodes          list inode information instead of block usage',
    '-k                    like --block-size=1K',
    '-l, --local           limit listing to local file systems',
    '-m                    like --block-size=1M',
    '-P, --portability     use the POSIX output format',
    '-T, --print-type      print file system type',
    '-t, --type=TYPE       limit listing to file systems of type TYPE',
    '-x, --exclude-type=TYPE  limit listing to file systems not of type TYPE',
    '--total               produce a grand total',
    '',
    '“The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.” ~ Daniel J. Boorstin',
  ],
  echo: [
    'echo',
    'Display a line of text.',
    '',
    'Syntax',
    'echo [SHORT-OPTION]... [STRING]...',
    'echo LONG-OPTION',
    '',
    'Description',
    'Echo the STRING(s) to standard output.',
    '',
    'Options',
    '-n do not output the trailing newline',
    '-e enable interpretation of backslash escapes',
    '-E disable interpretation of backslash escapes (default)',
    '',
    'The echo command is a built-in command in most Unix-like operating systems that allows you to display a line of text on the standard output or a file. It is commonly used in shell scripts and batch files to output status text to the screen or a file.',
    '',
    'Examples',
    'Display a line of text:',
    '$ echo "Hello, World!"',
    'Display a line of text without a newline:',
    '$ echo -n "Hello, World!"',
    'Display a line of text with backslash escapes:',
    '$ echo -e "Hello,\\nWorld!"',
    '',
    '“The only way to do great work is to love what you do.” ~ Steve Jobs',
  ],
  ls: [
    'ls',
    'List directory contents.',
    '',
    'Syntax',
    'ls [-Option(s)] [file ...]',
    "ls-F [-Option(s)] [file ...] This built-in is just like 'ls -F', but much faster.",
    "l List files in long format 'ls -l'",
    "ll List files in long format, showing invisible files `ls -la'",
    '',
    'Options',
    '-@ Display extended attribute keys and sizes.',
    "-1 (The numeric digit 'one'.)  Force output to be one entry per line. This is the default when output is not to a terminal.",
    '-A List all entries including those starting with a dot . Except for . and .. This option is always set for the superuser (via sudo).',
    '-a List all entries including those starting with a dot .',
    '-B Force printing of non-printable characters (as defined by ctype(3) and current locale settings) in file names as \\xxx, where xxx is the numeric value of the character in octal.',
    '-b As -B, but use C escape codes whenever possible.',
    '-C Force multi-column output; this is the default when output is to a terminal.',
    '-c Use time when file status was last changed for sorting or printing.',
    '-d Directories are listed as plain files (not searched recursively).',
    '-D format When printing in the long (-l) format, use format to format the date and time output. The argument format is a string used by strftime(3). Depending on the choice of format string, this may result in a different number of columns in the output.  This option overrides the -T option. This option is not defined in POSIX.1.',
    '-F Display a slash / immediately after each pathname that is a directory, an asterisk * after each that is executable, an at sign @ after each symbolic link, an equals sign = after each socket, a percent sign % after each whiteout, and a vertical bar | after each that is a FIFO.',
    '-f Output is not sorted.',
    '-G Enable colour output. This option is equivalent to defining CLICOLOR or COLORTERM in the environment and setting --color=auto. (See below.)',
    '-g This option is deprecated. This option is only available for compatibility with POSIX; it is used to display the group name in the long (-l) format output (the owner name is suppressed).',
    '-H Symbolic links on the command line are followed. This option is assumed if none of the -F, -d, or -l options are specified.',
    '-h When used with the -l option, use unit suffixes: Byte, Kilobyte, Megabyte, Gigabyte, Terabyte and Petabyte in order to reduce the number of digits to three or less using base 2 for sizes.',
    "-i For each file, print the file's file serial number (inode number).",
    '-k If the -s option is specified, print the file size allocation in kilobytes, not blocks.  This option overrides the environment variable BLOCKSIZE.',
    '-L If argument is a symbolic link, list the file or directory the link references rather than the link itself.  This option cancels the -P option.',
    '-l List in long format. Ownership, Date/Time etc (See below) For terminal output, a total sum of all the file sizes is output on a line before the long listing. If the file is a symbolic link the pathname of the linked-to file is preceded by ->',
    '-m Stream output format; list files across the page, separated by commas.',
    '-n Display user and group IDs numerically rather than converting to a user or group name in a long (-l) output. This option turns on the -l option.',
    '-O Include the file flags in a long (-l) output.',
    '-o List in long format, but omit the group id.',
    '-P If argument is a symbolic link, list the link itself rather than the object the link references.  This option cancels the -H and -L options.',
    '-p Write a slash (/) after each filename if that file is a directory.',
    "-q Force printing of non-graphic characters in file names as the character '?'; this is the default when output is to a terminal.",
    '-R Recursively list subdirectories encountered.',
    '-r Reverse the order of the sort to get reverse lexicographical order or the oldest entries first. (or largest files last, if combined with sort by size)',
    '-S Sort files by size',
    '-s Display the number of file system blocks actually used by each file, in units of 512 bytes, where partial units are rounded up to the next integer value.   If the output is to a terminal, a total sum for all the file sizes is output on a line before the listing.  The environment variable BLOCKSIZE overrides the unit size of 512 bytes.',
    "-T When used with the -l (lowercase letter 'ell') option, display complete time information for the file, including month, day, hour, minute, second, and year.",
    '-t Sort by time modified (most recently modified first) before sorting the operands by lexicographical order.',
    '-u Use time of last access, instead of last modification of the file for sorting (-t) or printing (-l).',
    '-v Force unedited printing of non-graphic characters. This is the default when output is not to a terminal.',
    '-W Display whiteouts when scanning directories. (-S) flag).',
    '-w Force raw printing of non-printable characters.  This is the default when output is not to a terminal.',
    '-x The same as -C, except that the multi-column output is produced with entries sorted across, rather than down, the columns.',
    'The -1, -C, -x, and -l options all override each other; the last one specified determines the format used.',
    'The -c and -u options override each other; the last one specified determines the file time used.',
    'The -B, -b, -w, and -q options all override each other; the last one specified determines the format used for non-printable characters.',
    'The -H, -L and -P options all override each other (either partially or fully); they are applied in the order specified.',
    'By default, ls lists one entry per line to standard output; the exceptions are to terminals or when the -C or -x options are specified.',
    'File information is displayed with one or more <blank>s separating the information associated with the -i, -s, and -l options.',
    "ls is pronounced as the two letters: 'ell ess'",
    '',
    'The Long Format',
    'If the -l option is given, the following information is displayed for each file: file mode, number of links, owner name, group name, number of bytes in the file, abbreviated month, day-of-month file was last modified, hour file last modified, minute file last modified, and the pathname.',
    'In addition, for each directory whose contents are displayed, the total number of 512-byte blocks used by the files in the directory is displayed on a line by itself, immediately before the information for the files in the directory.',
    'If the file or directory has extended attributes, the permissions field printed by the -l option is followed by an @ character. Otherwise, if the file or directory has extended security information, the permissions field printed by the -l option is followed by a + character.',
    'If the modification time of the file is more than 6 months in the past or future, then the year of the last modification is displayed in place of the hour and minute fields.',
    "If the owner or group names are not a known user or group name, or the -n option is given, the numeric ID's are displayed.",
    "If the file is a character special or block special file, the major and minor device numbers for the file are displayed in the size field. If the file is a symbolic link, the pathname of the linked-to file is preceded by '->'",
    'The file mode printed under the -l option consists of the entry type, owner permissions, and group permissions. The entry type character describes the type of file, as follows:',
    'b Block special file.',
    'c Character special file.',
    'd Directory.',
    'l Symbolic link.',
    's Socket link.',
    'p FIFO.',
    '- Regular file.',
    'The next three fields are three characters each: owner permissions, group permissions, and other permissions. Each field has three character positions:',
    '1. If r, the file is readable; if -, it is not readable.',
    '2. If w, the file is writable; if -, it is not writable.',
    '3. The first of the following that applies:',
    'S If in the owner permissions, the file is not executable and set-user-ID mode is set. If in the group permissions, the file is not executable and set-group-ID mode is set.',
    's If in the owner permissions, the file is executable and set-user-ID mode is set. If in the group permissions, the file is executable and setgroup-ID mode is set.',
    'x The file is executable or the directory is searchable.',
    '- The file is neither readable, writable, executable, nor set-user-ID nor set-group-ID mode, nor sticky. (See below.)',
    'These next two apply only to the third character in the last group (other permissions).',
    'T The sticky bit is set (mode 1000), but not execute or search permission. (See chmod(1) or sticky(8).)',
    't The sticky bit is set (mode 1000), and is searchable or executable. (See chmod(1) or sticky(8).)',
    "ls-F passes its arguments to ls if it is given any switches, so `alias ls ls-F' generally does the right thing.",
    'Color ls Listings',
    'To set up colour labeling, put the following in your ~/.bash_profile file (assuming bash is your default macOS shell):',
    "export CLICOLOR='Yes'",
    'You can also customise the colors further by setting the LSCOLORS variable.',
    'Other ls Environment Settings',
    '',
    'Examples',
    'List the filenames in the current folder:',
    '$ ls',
    'List the filenames with their characteristics (Size, Privs, Owner, etc):',
    '$ ls -l',
    'List the filenames with Size, Privs, Owner + Flags (-o option):',
    '$ ls -lo',
    'List the filenames sorted by time modified (most recent first):',
    '$ ls -lt',
    'List ALL files (including hidden):',
    '$ ls -a',
    'List iPhone backup files:',
    '$ ls -l ~/Library/iTunes/iPhone\\ Software\\ Updates',
    'or',
    "$ ls -l ~/'Library/iTunes/iPhone Software Updates'",
    'List all the file links in the current folder - in the ouptut of ls each symbolic directory has l permission at the begining of the permission flags, so grep ^l will list only symbolic links:',
    '$ ls -lR | grep ^l',
    'A less cryptic method is to use find . -type l',
    'Include a special character at the end that tells you what kind of file it is:',
    '$ ls -F',
    'List .jpg files:',
    '$ ls *.jpg',
    "Filenames beginning with 'a':",
    '$ ls a*',
    "Filenames containing 'att'",
    '$ ls *att*',
    'Long list + show all + follow symlinks w. dest:',
    '$ ls -lahL',
    'List sorted by Size:',
    '$ ls -l | sort -n +4',
    'or',
    '$ ls -lrS',
    'List all subdirectories:',
    '$ ls *',
    'Loop through all the files in a folder, note the use of quotes to cope with filenames that include spaces:',
    '$ ls | while read FILE; do echo "$FILE"; done',
    'List all files, one per line, including subdirectories - using find:',
    '$ find ~/Documents/ -type f',
    '',
    '“If the doors of perception were cleansed every thing would appear to man as it is, infinite” ~ William Blake',
  ],
  ifconfig: [
    'ifconfig',
    'Configure network interface parameters. The ifconfig utility is used to assign an address to a network interface and/or configure network interface parameters.',
    'Syntax',
    'ifconfig [-L] [-m] [-r] interface [create] [address_family] [address [dest_address]] [parameters]',
    'ifconfig interface destroy',
    'ifconfig -a [-L] [-d] [-m] [-r] [-u] [-v] [address_family]',
    'ifconfig -l [-d] [-u] [address_family]',
    'ifconfig [-L] [-d] [-m] [-r] [-u] [-v] [-C]',
    'ifconfig interface vlan vlan-tag vlandev iface',
    'ifconfig interface -vlandev iface',
    'ifconfig interface bonddev iface',
    'ifconfig interface -bonddev iface',
    'ifconfig interface bondmode lacp | static',
    'Options:',
    'address',
    'address_family',
    'dest_address',
    'interface',
    'The following parameters can be set with ifconfig:',
    'add',
    'alias',
    '-alias',
    'anycast',
    'arp',
    '-arp',
    'broadcast',
    'debug',
    '-debug',
    'delete',
    'down',
    'ether',
    'lladdr addr',
    'media type',
    'mediaopt opts',
    '-mediaopt opts',
    'create',
    'destroy',
    'plumb',
    'unplumb',
    'metric n',
    'mtu n',
    'netmask mask',
    'prefixlen len',
    'remove',
    'link[0-2]',
    '-link[0-2]',
    'up',
    'bonddev iface',
    '-bonddev iface',
    'bondmode lacp | static',
    'tunnel src_addr dest_addr',
    '-tunnel',
    'deletetunnel',
    'addm interface',
    'deletem interface',
    'maxaddr size',
    'timeout seconds',
    'addr',
    'static interface-name address',
    'deladdr address',
    'flush',
    'flushall',
    'discover interface',
    '-discover interface',
    'learn interface',
    '-learn interface',
    'sticky interface',
    '-sticky interface',
    'private interface',
    '-private interface',
    'span interface',
    '-span interface',
    'stp interface',
    '-stp interface',
    'edge interface',
    '-edge interface',
    'autoedge interface',
    '-autoedge interface',
    'ptp interface',
    '-ptp interface',
    'autoptp interface',
    '-autoptp interface',
    'maxage seconds',
    'fwddelay seconds',
    'hellotime seconds',
    'priority value',
    'proto value',
    'holdcnt value',
    'ifpriority interface value',
    'ifpathcost interface value',
    'ifmaxaddr interface size',
    'vlan vlan_tag',
    'vlandev iface',
    '-vlandev [iface]',
    'Diagnostics',
    'NOTES',
    'Examples',
    'Display the mac address for en0 (via StackOverflow):',
    "$ ifconfig en0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'",
    'Spoof a new mac address (n.b. this will not work for 2018+ MacBook Pros running High Sierra or newer - fails silently):',
    '$ sudo ifconfig en0 ether new_mac_address',
    'Assign the IPv4 address 192.0.2.10, with a network mask of 255.255.255.0, to the interface en0:',
    '$ ifconfig en0 inet 192.0.2.10 netmask 255.255.255.0',
    'Add the IPv4 address 192.0.2.45, with the CIDR network prefix /28, to the interface en0, using add as a synonym for the canonical form of the option alias:',
    '$ ifconfig en0 inet 192.0.2.45/28 add',
    'Remove the IPv4 address 192.0.2.45 from the interface en0:',
    '$ ifconfig en0 inet 192.0.2.45 -alias',
    'Add the IPv6 address 2001:DB8:DBDB::123/48 to the interface en0:',
    '$ ifconfig en0 inet6 2001:db8:bdbd::123 prefixlen 48 alias',
    'Remove the IPv6 address added in the above example, using the / character as shorthand for the network prefix, and using delete as a synonym for the canonical form of the option -alias:',
    '$ ifconfig en0 inet6 2001:db8:bdbd::123/48 delete',
    'Configure the interface en1, to use 100baseTX, full duplex Ethernet media options:',
    '$ ifconfig en1 media 100baseTX mediaopt full-duplex',
    'Create the software network interface gif1:',
    '$ ifconfig gif1 create',
    'Destroy the software network interface gif1:',
    '$ ifconfig gif1 destroy',
    'BSD June 20, 2008',
    '“A Connection Manager connection does not connect after being disconnected” ~ Title of Microsoft KnowledgeBase KB325331',
  ],
  man: [
    'man',
    'Format and Display the On-line Manual Pages',
    '',
    'Syntax',
    'man [options] [[section] page ...]',
    '',
    'Description',
    "The 'man' command is used to format and display the manual pages of commands and other system components. It provides users with detailed information, such as descriptions, options, usage, and examples.",
    '',
    'Options',
    '-f, --whatis   Equivalent to whatis. Display a short description from the manual page.',
    '-k, --apropos  Search the manual page names and descriptions for a keyword.',
    '-K, --global-apropos  Search for text in all manual pages.',
    '-t, --troff    Use groff to format the manual page, with an output suitable for a printer.',
    '-X, --gxditview  Display the formatted manual page in a graphical window using gxditview (if available).',
    '-Z, --ditroff  Generate output in ditroff format.',
    '-l, --local-file  Interpret page argument(s) as local filename(s).',
    '-p, --preprocessor  Specify the preprocessor to use (e.g., eqn, pic).',
    '-H, --html     Display the manual page in HTML format.',
    "If the section is not specified, 'man' will look for the page in all sections of the manual.",
    '',
    'Examples',
    'To view the manual page for the ls command:',
    '$ man ls',
    "To find all pages related to the keyword 'list':",
    '$ man -k list',
    'To display the manual page for the ls command in HTML format:',
    '$ man -H ls',
    '',
    'Notes',
    "The availability of certain options and the behavior of 'man' can vary between Unix and Unix-like systems.",
    '',
    '“An investment in knowledge pays the best interest.” ~ Benjamin Franklin',
  ],
  uname: [
    'uname',
    'Print system information',
    '',
    'Syntax',
    'uname [OPTION]...',
    '',
    'Description',
    'Print certain system information.  With no OPTION, same as -s.',
    '',
    'Options',
    '-a, --all                print all information, in the following order:',
    '  -s, --kernel-name      print the kernel name',
    '  -n, --nodename         print the network node hostname',
    '  -r, --kernel-release   print the kernel release',
    '  -v, --kernel-version   print the kernel version',
    '  -m, --machine          print the machine hardware name',
    '  -p, --processor        print the processor type (non-portable)',
    '  -i, --hardware-platform print the hardware platform (non-portable)',
    '  -o, --operating-system print the operating system',
    '',
    '“The only true wisdom is in knowing you know nothing.” ~ Socrates',
  ],
  ps: [
    'ps',
    'Report a snapshot of the current processes.',
    '',
    'Syntax',
    'ps [options]',
    '',
    'Description',
    'ps displays information about a selection of the active processes. If you want a repetitive update of the selection and the displayed information, use top(1) instead.',
    '',
    'Options',
    '-A Select all processes.',
    '-a Select all processes except both session leaders (see getsid(2)) and processes not associated with a terminal.',
    '-d Select all processes except session leaders.',
    '-e Select all processes. Identical to -A.',
    '-N Select all processes except those that fulfill the specified conditions (negates the selection).',
    '-T Select all processes associated with this terminal.',
    '-x Select processes without controlling ttys.',
    '-c Show the true command name.',
    '-f Do full-format listing. This option can be combined with many other UNIX-style options to add additional columns. It also causes the command arguments to be printed. When used with -L, the NLWP (number of threads) and LWP (thread ID) columns will be added. See the c option, the format keyword args, and the format keyword comm.',
    '-j Jobs format.',
    '-l Long format. In this format, the process ID (pid) is displayed as PID. The format keyword args is an alias for the -o pid,format option.',
    '-y Do not show flags; show rss in place of addr.',
    '-Z Add the zone name.',
    '-O Add the zone event port.',
    '-M Add the zone ID.',
    '-p pidlist Select by process ID. This selects the processes whose process ID numbers appear in pidlist. Identical to -o pid=.',
    '-g grplist Select by real group ID (RGID) or name. Identical to -o rgroup=.',
    '-G pgrplist Select by effective group ID (EGID) or name. Identical to -o group=.',
    '-u userlist Select by effective user ID (EUID) or name. Identical to -o user=.',
    '-U userlist Select by real user ID (RUID) or name. Identical to -o ruser=.',
    '-k kernellist Select by kernel process ID (kid) or name. Identical to -o kernel=.',
    '-c class Select by scheduling class. Identical to -o class=.',
    '-m Select by memory mapping.',
    '-n namelist Select by name list.',
    '-o format user-defined format. format is a single argument in the form of a blank-separated or comma-separated list, which offers a way to specify individual output columns. The recognized keywords are described in the STANDARD FORMAT SPECIFIERS section below. Headers may be renamed (ps -o pid,ruser=RealUser -o comm=Command) as desired. If all column headers are empty (ps -o pid= -o comm=) then the header line will not be output. Column width will increase as needed for wide headers; this may be used to widen up columns such as WCHAN (ps -o pid,wchan=WIDE-WCHAN-COLUMN -o comm). Explicit width control (ps opid,wchan:42,cmd) is offered too. The behavior of ps -o pid=X,comm=Y varies with personality; output may be one column named "X,comm=Y" or two columns named "X" and "Y". Use multiple -o options when in doubt. Use the PS_FORMAT environment variable to specify a default as desired; DefSysV and DefBSD are macros that may be used to choose the default UNIX or BSD columns.',
    '-O format Like -o, but preloaded with some default columns. The default display is still subject to change.',
    '-y Do not show flags; show rss in place of addr.',
    '-Z Add the zone name.',
    '',
    '“The only way to make sense out of change is to plunge into it, move with it, and join the dance.” ~ Alan Watts',
  ],
  pwd: [
    'pwd',
    'Print Working Directory - the absolute pathname of the current folder (i.e. it tells you where you are).',
    '',
    'Syntax',
    'pwd [-LP]',
    '',
    'Key',
    '-P The pathname printed contains no symbolic links',
    '-L The pathname printed can contain symbolic links.',
    'Enabling the -o physical option for the set builtin command is equivalent to -P.',
    'The return status is 0 unless an error occurs while reading the name of the current directory or an invalid option is supplied.',
    'Some shells provide a builtin pwd command which is similar or identical to this utility.',
    '',
    '“Take care of your body. It’s the only place you have to live” ~ Jim Rohn',
  ],
  traceroute: [
    'traceroute',
    'Print the route packets take to network host.',
    '',
    'Syntax',
    'traceroute [-46dFITUnreAV] [-f first_ttl] [-g gateway] [-i iface] [-M first_ttl] [-m max_ttl] [-p port] [-q nqueries] [-s src_addr] [-t tos] [-w waittime] [-z pausemsecs] host [packetlen]',
    '',
    'Description',
    "traceroute tracks the route packets taken from an IP network on their way to a given host. It utilizes the IP protocol's time to live (TTL) field and attempts to elicit an ICMP TIME_EXCEEDED response from each gateway along the path to the host.",
    '',
    'Options',
    '-4 Use IPv4 only.',
    '-6 Use IPv6 only.',
    '-d Enable socket-level debugging.',
    '-F Do not fragment packets.',
    '-I Use ICMP ECHO instead of UDP datagrams.',
    '-T Use TCP SYN for probes.',
    '-U Use UDP to particular port for traceroute.',
    '-n Do not resolve IP addresses to hostnames.',
    '-r Bypass the normal routing tables and send directly to a host on an attached network.',
    '-e Show ICMP extensions (if present), including MPLS labels.',
    '-A Use AS path lookups in routing registries (BGP routing data).',
    '-V Show version information.',
    '-f first_ttl Start from the first_ttl hop (instead of 1).',
    '-g gateway Use a loose source route gateway (8 max).',
    '-i iface Use a specified interface or source address.',
    '-M first_ttl Start from the first_ttl hop (IPv6 only).',
    '-m max_ttl Set the max number of hops (max TTL to be reached).',
    '-p port Use a particular destination port.',
    '-q nqueries Set the number of probes per hop count.',
    '-s src_addr Use a particular source address.',
    '-t tos Set the TOS (IPv4 Type of Service) or TC (IPv6 Traffic Class) value.',
    '-w waittime Set the number of seconds to wait for a response.',
    '-z pausemsecs Set the time in milliseconds to pause between probes.',
    'host The destination host name or IP address.',
    'packetlen The total length of the outgoing packet.',
    '',
    '“The only way to make sense out of change is to plunge into it, move with it, and join the dance.” ~ Alan Watts',
  ],
  theme: [
    'theme',
    'Change the Terminal Theme - Modify the appearance of the terminal interface.',
    '',
    'Syntax',
    'theme [color]',
    '',
    'Description',
    "The 'theme' command changes the color scheme of the terminal to the specified color. It allows users to customize the look and feel of their terminal interface for better readability or personal preference.",
    '',
    'Options',
    `Available colors: ${themeColors.join(', ')}.`,
    'If no color is specified, the command will revert the terminal to the default theme.',
    '',
    'Examples',
    'To change the terminal theme to blue:',
    '$ theme blue',
    'To revert to the default terminal theme:',
    '$ theme',
    '',
    'Notes',
    "The 'theme' command relies on the terminal emulator's ability to change color schemes. Not all terminal emulators may support this feature.",
    '',
    '“The secret of change is to focus all of your energy not on fighting the old, but on building the new.” ~ Socrates',
  ],
  whoami: [
    'whoami',
    'Print the current user id and name. Same as id -un.',
    '',
    'Syntax',
    'whoami [options]',
    '',
    'Options',
    '--help Display Help',
    '--version Display program version info',
    "The whoami utility has been obsoleted by the id(1) utility, and is equivalent to 'id -un'.",
    "The command 'id -p' is suggested for normal interactive use.",
    'The whoami utility displays your effective user ID as a name.',
    '',
    '“The more the merrier” ~ John Heywood',
  ],
};
